// Auth-gated proxy: stream a pre-generated waveform PNG by sha1(path).
// Forwards to the M1 engine's GET /waveform/<sha1>.png endpoint, which
// serves files from ~/automation/data/waveforms/ generated by the sweeper
// (~/automation/sweeper/).
//
// 404 from the engine (PNG doesn't exist yet, sweeper hasn't covered that
// file, TCC-blocked, or unrenderable) is forwarded as-is so BucketCard's
// <img onerror> can swap in its placeholder. Auth enforced upstream by
// src/middleware.ts.

import type { APIRoute } from "astro";
import { streamWaveform } from "../../../lib/console-api";

const SHA1_RE = /^[a-f0-9]{40}$/;

export const GET: APIRoute = async ({ url }) => {
  const sha1 = (url.searchParams.get("sha1") ?? "").toLowerCase();
  if (!SHA1_RE.test(sha1)) {
    return new Response(
      JSON.stringify({ error: "sha1 query param required (40 hex chars)" }),
      { status: 400, headers: { "content-type": "application/json" } },
    );
  }

  const res = await streamWaveform(sha1);

  if (res.status === 404) {
    // Forward as 404 with a tiny JSON so the browser sees a clean miss.
    return new Response(JSON.stringify({ error: "waveform not yet generated" }), {
      status: 404,
      headers: { "content-type": "application/json" },
    });
  }

  if (!res.ok) {
    return new Response(
      JSON.stringify({ error: `engine ${res.status}` }),
      { status: 502, headers: { "content-type": "application/json" } },
    );
  }

  // Pass the PNG through. Cache for a day; sweeper re-runs daily so any
  // late-arriving renders will be picked up by next-day requests.
  return new Response(res.body, {
    status: 200,
    headers: {
      "content-type": "image/png",
      "cache-control": "public, max-age=86400",
    },
  });
};
